/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkspaces"];
        put?: never;
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateWorkspace"];
        trace?: never;
    };
    "/workspaces/{workspaceId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        get: operations["listWorkspaceMembers"];
        put?: never;
        post: operations["addWorkspaceMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeWorkspaceMember"];
        options?: never;
        head?: never;
        patch: operations["updateWorkspaceMember"];
        trace?: never;
    };
    "/workspaces/{workspaceId}/todos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        get: operations["listTodos"];
        put?: never;
        post: operations["createTodo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/todos/{todoId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                todoId: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        get: operations["getTodo"];
        put?: never;
        post?: never;
        delete: operations["deleteTodo"];
        options?: never;
        head?: never;
        patch: operations["updateTodo"];
        trace?: never;
    };
    "/workspaces/{workspaceId}/todos/{todoId}/dependencies": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                todoId: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addTodoDependency"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/todos/{todoId}/dependencies/{dependsOnId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                todoId: components["parameters"]["TodoId"];
                dependsOnId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeTodoDependency"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspaceId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        get: operations["streamWorkspaceEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail: string;
            instance?: string;
            code?: string;
            errors?: {
                [key: string]: string[];
            };
            affectedTodos?: components["schemas"]["AffectedTodo"][];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
        };
        RegisterInput: {
            /** Format: email */
            email: string;
            password: string;
            displayName: string;
            workspaceName: string;
            /** @example Asia/Kuala_Lumpur */
            timezone: string;
        };
        LoginInput: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthResponse: {
            user: components["schemas"]["User"];
            csrfToken: string;
            workspaces: components["schemas"]["Workspace"][];
        };
        CurrentUserResponse: components["schemas"]["AuthResponse"];
        /** @enum {string} */
        WorkspaceRole: "owner" | "editor" | "viewer";
        /** @enum {string} */
        EditableRole: "editor" | "viewer";
        Workspace: {
            /** Format: uuid */
            id: string;
            name: string;
            timezone: string;
            role: components["schemas"]["WorkspaceRole"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        WorkspaceInput: {
            name: string;
            timezone: string;
        };
        WorkspaceMember: {
            /** Format: uuid */
            userId: string;
            /** Format: email */
            email: string;
            displayName: string;
            role: components["schemas"]["WorkspaceRole"];
            /** Format: date-time */
            joinedAt: string;
        };
        /** @enum {string} */
        TodoStatus: "NotStarted" | "InProgress" | "Completed" | "Archived";
        /** @enum {string} */
        TodoPriority: "Low" | "Medium" | "High";
        RecurrenceInput: {
            intervalCount: number;
            /** @enum {string} */
            intervalUnit: "day" | "week" | "month";
        };
        Recurrence: components["schemas"]["RecurrenceInput"] & {
            /** Format: uuid */
            seriesId: string;
            sequence: number;
            anchorLocal: string;
        };
        TodoDependency: {
            /** Format: uuid */
            id: string;
            name: string;
            status: components["schemas"]["TodoStatus"];
            completed: boolean;
        };
        Todo: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspaceId: string;
            name: string;
            description: string;
            /** Format: date-time */
            dueAt: string;
            status: components["schemas"]["TodoStatus"];
            priority: components["schemas"]["TodoPriority"];
            version: number;
            blocked: boolean;
            blockingDependencyIds: string[];
            dependencies: components["schemas"]["TodoDependency"][];
            recurrence?: components["schemas"]["Recurrence"] | null;
            completedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateTodoInput: {
            name: string;
            description: string;
            /** Format: date-time */
            dueAt: string;
            status: components["schemas"]["TodoStatus"];
            priority: components["schemas"]["TodoPriority"];
            recurrence?: components["schemas"]["RecurrenceInput"] | null;
            dependencyIds?: string[];
        };
        UpdateTodoInput: {
            name?: string;
            description?: string;
            /** Format: date-time */
            dueAt?: string;
            status?: components["schemas"]["TodoStatus"];
            priority?: components["schemas"]["TodoPriority"];
            /** @default false */
            cascadeDependents: boolean;
        };
        TodoMutationResponse: {
            todo: components["schemas"]["Todo"];
            generatedOccurrenceId?: string | null;
        };
        TodoList: {
            items: components["schemas"]["Todo"][];
            nextCursor?: string | null;
            hasMore: boolean;
        };
        AffectedTodo: {
            /** Format: uuid */
            id: string;
            name: string;
            status: components["schemas"]["TodoStatus"];
        };
    };
    responses: {
        /** @description RFC 9457 Problem Details */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        WorkspaceId: string;
        TodoId: string;
        CsrfToken: string;
        /** @description Strong or weak ETag containing the current integer version. */
        IfMatch: string;
    };
    requestBodies: never;
    headers: {
        /** @description Current TODO version */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterInput"];
            };
        };
        responses: {
            /** @description Registered and signed in */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated user and CSRF token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspaces visible to the current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Workspace"][];
                    };
                };
            };
        };
    };
    createWorkspace: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceInput"];
            };
        };
        responses: {
            /** @description Created workspace */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    updateWorkspace: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceInput"];
            };
        };
        responses: {
            /** @description Updated workspace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listWorkspaceMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["WorkspaceMember"][];
                    };
                };
            };
        };
    };
    addWorkspaceMember: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    role: components["schemas"]["EditableRole"];
                };
            };
        };
        responses: {
            /** @description Added member */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMember"];
                };
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    removeWorkspaceMember: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Problem"];
        };
    };
    updateWorkspaceMember: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    role: components["schemas"]["EditableRole"];
                };
            };
        };
        responses: {
            /** @description Updated member */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMember"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    listTodos: {
        parameters: {
            query?: {
                status?: components["schemas"]["TodoStatus"][];
                priority?: components["schemas"]["TodoPriority"][];
                dueFrom?: string;
                dueTo?: string;
                dependencyState?: "blocked" | "unblocked";
                sort?: "dueAt" | "priority" | "status" | "name";
                direction?: "asc" | "desc";
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Keyset-paginated TODOs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoList"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    createTodo: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTodoInput"];
            };
        };
        responses: {
            /** @description Created TODO */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    getTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                todoId: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TODO details */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    deleteTodo: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                /** @description Strong or weak ETag containing the current integer version. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                todoId: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soft deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
        };
    };
    updateTodo: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                /** @description Strong or weak ETag containing the current integer version. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                todoId: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTodoInput"];
            };
        };
        responses: {
            /** @description Updated TODO and optionally generated recurrence occurrence */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoMutationResponse"];
                };
            };
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    addTodoDependency: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                /** @description Strong or weak ETag containing the current integer version. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                todoId: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    dependsOnId: string;
                };
            };
        };
        responses: {
            /** @description Dependency added */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
        };
    };
    removeTodoDependency: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                /** @description Strong or weak ETag containing the current integer version. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                todoId: components["parameters"]["TodoId"];
                dependsOnId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependency removed */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            412: components["responses"]["Problem"];
        };
    };
    streamWorkspaceEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent event stream of committed workspace changes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
}
