import { hashPassword } from "../auth/password.js";
import { loadConfig } from "../config.js";
import { createPool, inTransaction } from "../platform/db.js";

const config = loadConfig();
const pool = createPool(config);
const userId = "018f0000-0000-7000-8000-000000000001";
const workspaceId = "018f0000-0000-7000-8000-000000000002";
const passwordHash = await hashPassword("demo-password-123");

await inTransaction(pool, async (client) => {
  await client.query(
    `INSERT INTO users (id, email, display_name, password_hash)
     VALUES ($1, 'demo@example.com', 'Demo User', $2)
     ON CONFLICT (email) DO UPDATE SET password_hash = EXCLUDED.password_hash`,
    [userId, passwordHash],
  );
  await client.query(
    `INSERT INTO workspaces (id, name, timezone)
     VALUES ($1, 'Demo Workspace', 'Asia/Kuala_Lumpur') ON CONFLICT (id) DO NOTHING`,
    [workspaceId],
  );
  await client.query(
    `INSERT INTO workspace_members (workspace_id, user_id, role)
     VALUES ($1, $2, 'owner') ON CONFLICT DO NOTHING`,
    [workspaceId, userId],
  );
  await client.query(
    `INSERT INTO todos
      (id, workspace_id, name, description, due_at, status, priority, completed_at, created_by, updated_by)
     SELECT
       ('00000000-0000-7000-8000-' || lpad(n::text, 12, '0'))::uuid,
       $1,
       'Seed TODO ' || lpad(n::text, 5, '0'),
       'Performance fixture generated by make seed.',
       clock_timestamp() + ((n % 365) || ' days')::interval,
       n % 4,
       n % 3,
       CASE WHEN n % 4 = 2 THEN clock_timestamp() ELSE NULL END,
       $2,
       $2
     FROM generate_series(1, 100) AS n
     ON CONFLICT (id) DO NOTHING`,
    [workspaceId, userId],
  );
});

const count = await pool.query<{ count: string }>(
  "SELECT count(*) FROM todos WHERE workspace_id = $1",
  [workspaceId],
);
process.stdout.write(
  `seeded workspace ${workspaceId} with ${count.rows[0]!.count} TODOs\n`,
);
process.stdout.write("demo login: demo@example.com / demo-password-123\n");
await pool.end();
